version: "3"
services:
  redis:
    image: redis
    ports:
      - "6479:6379"
  postgres:
    image: postgres
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
  s3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
    volumes:
      - s3data:/fakes3_root
  outline:
    image: outline:v001
    command: yarn dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pull: 1
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/outline
    depends_on:
      - postgres
      - redis
      - s3
  nginx:
    image: nginx
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/proxy.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
    depends_on:
      - postgres


volumes:
  s3data: